export const AUTH_ERROR_CODES = {
    AUTH_LOGIN_SUCCESS : "AUTH_LOGIN_SUCCESS",
    AUTH_NOT_AUTHORIZATION : "AUTH_NOT_AUTHORIZATION",
    AUTH_USER_DISABLE : "AUTH_USER_DISABLE",
    AUTH_INVALID_CREDENTIALS : "AUTH_INVALID_CREDENTIALS"
}
