export const ROL_CODES_MESSAGE = {
    ROL_CREATED: "ROL_CREATED",
    ROL_EXIST: "ROL_EXIST",
    ROL_PERMISSION_EMPTY: "ROL_PERMISSION_EMPTY",
    ROL_NOT_FOUND: "ROL_NOT_FOUND",
    ROL_DISABLE_SUCCESS : "ROL_DISABLE_SUCCESS",
    ROL_ENABLE_SUCCESS : "ROL_ENABLE_SUCCESS",
}