export const OPTIONS = {

    // SALES
    
    SALES_PRODUCTS: "SALES_PRODUCTS",
    SALES_BRANDS: "SALES_BRANDS",
    SALES_CLIENTS: "SALES_CLIENTS",

    // SETTINGS

    SETTING_USERS: "SETTING_USERS",
    SETTING_ROLS: "SETTING_ROLS"
}